events { }

http {
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    server {
        listen 80;

        location /health {
            proxy_pass http://health:5001;
        }

        location /api/ {
            proxy_pass http://api:5022/;
        }
    }
}
