// <auto-generated />
using System;
using Dinder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dinder.Infrastructure.Persistence.Migrations.Analytics
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260602085009_InitialAnalytics")]
    partial class InitialAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dinder.Infrastructure.Persistence.DailyActiveUser", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("daily_active_users", "analytics");
                });

            modelBuilder.Entity("Dinder.Infrastructure.Persistence.SubscriptionSnapshot", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Date", "Tier");

                    b.ToTable("subscription_snapshots", "analytics");
                });

            modelBuilder.Entity("Dinder.Infrastructure.Persistence.SwipeMetric", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRightSwipes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSwipes")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("swipe_metrics", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
