<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Dinder.Api</RootNamespace>
    <AssemblyName>Dinder.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dinder.Infrastructure\Dinder.Infrastructure.csproj" />
    <ProjectReference Include="..\Dinder.Application\Dinder.Application.csproj" />
    <ProjectReference Include="..\Dinder.Contracts\Dinder.Contracts.csproj" />
  </ItemGroup>

</Project>
