<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dinder.Application</RootNamespace>
    <AssemblyName>Dinder.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dinder.Domain\Dinder.Domain.csproj" />
    <ProjectReference Include="..\Dinder.Contracts\Dinder.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Gamification\achievements.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
